### ISSUE TITLE
Starting Thorium without a network causes null address

### ISSUE THREAD

**Issue by Emrix** [Thorium-Sim/thorium#1131]
## Description
Firstly, can we get some sort of recommendation as to what to include when submitting bugs? (Screenshots, Snap-shot files, step by step instructions, etc.)

Anyways I started Thorium Development server while not connected to a network, and for the address, to connect to the server, it pulls up `http://null:3000`.  I would expect this to show `http://localhost:3000` instead.

## Screenshot
![screen shot 2018-08-13 at 7 51 45 am](https://user-images.githubusercontent.com/1387836/44036069-2871573a-9ece-11e8-9ae6-57ac012c8fbd.png)

**Comment by alexanderson1993** [comment]
This shouldn't make a difference on localhost. You can still access it with `http://localhost:3000` or `http://127.0.0.1:3000`. Still, I'll make it so it defaults to `localhost` in the console output if no network is detected.
