### ISSUE TITLE
Damage Report Logistics

### ISSUE THREAD

**Issue by roslynsinclair** [Thorium-Sim/thorium#1171]
Our current reports have steps "linked" within them when using the panels. There will normally be a step at the beginning turning on a switch and then a step later turning it off again. I'm not sure how possible it would be, but making it so steps can be linked with one early in the report and one later in the report, or at least making a toggle on steps for it being required and pushing it to the end so we can have them turn off all of the switches at the end.

**Comment by alexanderson1993** [comment]
The concepts in this issue have been consolidated into #1267. Closing.
