### ISSUE TITLE
Translations in Klingon

### ISSUE THREAD

**Issue by Emrix** [Thorium-Sim/thorium#1186]
I want to be able to change my localization to Klingon!

**Comment by ksmithut** [comment]
Here's the page tracking unicode support: http://www.klingonwiki.net/En/Unicode

**Comment by alexanderson1993** [comment]
As cool as this would be, I think I'm going to close this one until Unicode gets it's act together more.

**Comment by brentjanderson** [comment]
Care to elaborate on what Unicode’s act is needing? I’m under the impression most everything is Unicode nowadays.

**Comment by alexanderson1993** [comment]
Klingon characters are not in Unicode, and I don’t think that Klingon is a locale option for browsers. So there are two big hurdles.
