### ISSUE TITLE
Add Dilithium Stress to Status screen

### ISSUE THREAD

**Issue by ksmithut** [Thorium-Sim/thorium#1189]
## Detailed Description

From this: https://github.com/Thorium-Sim/thorium/issues/1175

We need to add a Dilithium Stress component to the status screen that pulls info from the reactor like the Dilithium Stress Card does. It's not an interactive component, just needs to read the data and display the stress level like some of the other statuses (see screenshot below)

<img width="342" alt="screen shot 2018-08-25 at 17 57 55" src="https://user-images.githubusercontent.com/1906967/44623605-79fa3d80-a890-11e8-94bd-09885037f240.png">

**Comment by alexanderson1993** [comment]
Closed with #1188
