### ISSUE TITLE
Create offline card mechanism

### ISSUE THREAD

**Issue by alexanderson1993** [Thorium-Sim/thorium#14]
This will be attached to the card container, so it uses the same layout. it will default to 'Station Offline' text, and will lock out all access to other cards. Should also be included in the layouts themselves. Information about the offline status should be attached to the simulator object.

**Comment by brentjanderson** [comment]
One option would be to have a generic overlay card that can be applied. Essentially, you would set the station's overlay card to "offline" and that would trigger the desired effect. To set blackout, you would do the same. To set "destroyed" or "contaminated" or whatever would be the same. Refs #13. 

One downside to this approach is if you go from normal to offline to blackout and want to go back, you can't exactly "pop" the layout. That state would somehow need to be understood somewhere. 

Actually, this raises an interesting option: what if blackout and offline etc. were technically layouts, and you have a layout "stack" for each station. You push a layout on the station to switch to a new one, and you pop a layout to go back. This gives you flexible layout manipulation, and reversability.

**Comment by alexanderson1993** [comment]
Possible states:

* Maintenance
* Generic Offline
* Power Loss
* Lockdown

Additional States:
* Blackout
* "Borg" (though I'm not sure this will be used in the new universe)
* Soviet
* Hacking
