### ISSUE TITLE
Event sourcing optimizations

### ISSUE THREAD

**Issue by brentjanderson** [Thorium-Sim/thorium#159]
Animations are currently published frame by frame to the event queue. As animated entities are created, the number of events grows linearly. An optimization would be to only record user actions, and to separately record a stream of clock events that would be published at the fps desired. Animations would then be the result of the previous animation frame state and the delta in time frames. 

The above approach has the following trade offs:
1. Fewer events required at scale (one clock stream could feed any number of animations)
2. It's eventually consistent: animations will look identical everywhere as long as subscribers are up to date on events. If latency is low, then it will appear immediately consistent and accurate
3. You can dilate the clock issuing events so that as real time passes, simulation time speeds up or slows down
4. Unwinding events is not as trivial as undoing fully loaded animation frames, but it is still doable
5. You can compensate for latency using normal game strategies (e.g. Between keyframes, take the rates of motion or acceleration and infer what the next frames will be like)

**Comment by alexanderson1993** [comment]
Since I'm not really doing event sourcing, I'm just going to close this one.
