### ISSUE TITLE
Check to see if Thorium is already running on startup

### ISSUE THREAD

**Issue by Emrix** [Thorium-Sim/thorium#1619]
## Description

Many times when users are starting Thorium, particular in Linux, it starts running in the background, and users attempt to open it several times, creating several instances of it running.

Make a check on start up which checks to see if Thorium is already running.

**Comment by alexanderson1993** [comment]
@Emrix Are you planning on implementing this one?

**Comment by Emrix** [comment]
Yes, I am planning on implementing this one.  I'm just trying to figure out a good place to put it in the code.

**Comment by alexanderson1993** [comment]
The best place would be in the bootstrap, before anything else runs. /server/src/server.js is the best place to start. Just add the check before the first item in the promise chain, and have the check itself live in the /server/src/bootstrap folder. Get in touch if you have questions.
