### ISSUE TITLE
CRM114/Fighter Control

### ISSUE THREAD

**Issue by alexanderson1993** [Thorium-Sim/thorium#174]
<img width="834" alt="screen shot 2018-01-13 at 8 01 08 am" src="https://user-images.githubusercontent.com/6558157/34907195-08823bde-f838-11e7-870b-38f790ecd660.png">

**Comment by thoriumsim** [comment]
I would like to work on this.

**Comment by Emrix** [comment]
This is soon to be deployed, no?

**Comment by alexanderson1993** [comment]
It’s in progress.
