### ISSUE TITLE
External Docking ala Magellan

### ISSUE THREAD

**Issue by alexanderson1993** [Thorium-Sim/thorium#175]
![magellan quartermaster rev shuttle](https://user-images.githubusercontent.com/6558157/28332450-14dbc840-6bb2-11e7-9f89-fa4c838d4ee5.jpg)
![magellan quartermaster rev runaboutpads](https://user-images.githubusercontent.com/6558157/28332449-14b858ec-6bb2-11e7-93b5-0c867c033571.jpg)
![magellan quartermaster rev docking ports](https://user-images.githubusercontent.com/6558157/28332448-14b78192-6bb2-11e7-8bbb-ac18a0f0e832.jpg)

**Comment by jrobe** [comment]
Is this three cards? Or is this one card? Or is there a middle-ground approach that we'd want to take?

**Comment by alexanderson1993** [comment]
The screens are more for inspiration than anything. You can use them or do your own thing. Just make sure it works for multiple simulators.

**Comment by alexanderson1993** [comment]
To be clear, this should be one card. I suggest building it on the same foundation that the shuttles are built on.
