### ISSUE TITLE
Transwarp

### ISSUE THREAD

**Issue by connorlarsen1** [Thorium-Sim/thorium#1759]
If we could get a Transwarp type card that would be awesome, the Jump Drive aspect doesn't quite work the way we need it to. This would include: a subspace field card, a field power card (similar to subspace field but activating power levels to specific parts of the ship), and an actual activation/monitoring card.

**Comment by alexanderson1993** [comment]
What are you looking for with this? It sounds like three screens, right? How different would it be from the two-screen Magellan (2012) controls? (Screenshots below)


Also, how is this much different from the Jump Drive screen? This is a fairly niche request that is seemingly similar to the Jump Drive screen, so I would need to have a little bit more justification to bump the priority on this. 

<img width="846" alt="screen shot 2019-01-29 at 10 26 55 am" src="https://user-images.githubusercontent.com/6558157/51927273-783d2480-23b0-11e9-935b-1e6f3849f4cc.png">
<img width="846" alt="screen shot 2019-01-29 at 10 26 58 am" src="https://user-images.githubusercontent.com/6558157/51927275-7a06e800-23b0-11e9-958d-2b40b86c204b.png">

**Comment by connorlarsen1** [comment]
What we had on those controls would be perfect. I'm just trying to break up the control of things between the First Officer and the COO like we had it, so we can interconnect the jobs a bit more. The Jumpdrive option only connects to the one screen, and the interchangeable speed aspect is kind of an issue too, as the Transwarp just turns on and off, the speed thing adds some complications. It's also a bit intensive.
