### ISSUE TITLE
Specialized Docking Port

### ISSUE THREAD

**Issue by connorlarsen1** [Thorium-Sim/thorium#1760]
Is there a way to throw in permanent specialized docking ports kinda like what we had for the Ranger? Just a simple docking card where we could preset the name of the ship in the mission programming so its always that way on the controls.

**Comment by alexanderson1993** [comment]
<img width="846" alt="screen shot 2019-02-01 at 8 17 23 am" src="https://user-images.githubusercontent.com/6558157/52131709-ab72f400-25fa-11e9-95b4-987ecab273fc.png">

- Preset the name
- Allow for multiple specialized ports, ala Shuttlebays
- Link with rooms for cargo transferring purposes.
