### ISSUE TITLE
Computer Core

### ISSUE THREAD

**Issue by alexanderson1993** [Thorium-Sim/thorium#181]
Base it off of AWS, with the ability to spin up virtual machines, manage network connections, etc.
![screen shot 2018-05-11 at 4 05 31 pm](https://user-images.githubusercontent.com/6558157/39950728-a1071b80-5540-11e8-981f-d32dfcff75ad.png)
![screen shot 2018-05-11 at 5 27 29 pm](https://user-images.githubusercontent.com/6558157/39950729-a28510f2-5540-11e8-8d62-57502182a90e.png)
![screen shot 2018-05-11 at 4 05 24 pm](https://user-images.githubusercontent.com/6558157/39950732-a6b309ae-5540-11e8-940e-60524e75a7e7.png)

![computer core terminals](https://user-images.githubusercontent.com/6558157/32731581-74830f5a-c847-11e7-9208-73d4dc86af62.png)
![computer core users](https://user-images.githubusercontent.com/6558157/32731586-75eaf8c6-c847-11e7-9b87-6cc7b50ce9a0.png)

**Comment by G33kX** [comment]
To clarify: would this be a 'crew management' task for the player crew, or would it be an additional control card for the FD? If the latter, what would be the information/game system that needs virtual terminal management?

**Comment by alexanderson1993** [comment]
This would be more of a task for the player crew, and would be mostly hands-off for the flight director. This is based off the computer core cards from the Magellan.
