### ISSUE TITLE
Safari Doesn't Allow Textarea Inputs

### ISSUE THREAD

**Issue by Justintime50** [Thorium-Sim/thorium#1895]
## Detailed Description

If you try to input anything on Safari in a `textarea` specifically, it will not allow you to type anything. I got lucky a few times with a single letter before it quit. Other inputs seem to work fine.

**Comment by Emrix** [comment]
@Justintime50, do you have any specific steps to reproduce this issue?  IE: which card/view you are looking at, how to get there, etc.

**Comment by alexanderson1993** [comment]
It is confirmed to be an issue. The login screen exhibits this issue.

**Comment by Justintime50** [comment]
@Emrix yes it's always reproducible. I found it to only exhibit itself in `textarea` inputs as simple `input` items like a name or value work but large notes/description inputs won't allow for selection. You can see this mostly on the FD side of things (configuring flights and missions etc) where there are many `textarea` inputs.
