### ISSUE TITLE
Disable Systems If No Power

### ISSUE THREAD

**Issue by Justintime50** [Thorium-Sim/thorium#1896]
## Detailed Description

I've noticed a lot of the systems don't penalize users for a lack of power in the entire flight or to their system. (reactor, sensors, etc) I'm understanding of the reasons for that per the convo below, but I'd love to have some of these as automated as possible to pull some time off the FD. What if there were a toggle switch to allow for "easy mode" or "hard mode"? Easy mode would allow for forgiveness like this (if you were working with a school or kids event) and hard mode for an adult or teen event. That would give options and make one less thing the FD has to constantly manage, the system could do the work.

![Screen Shot 2019-03-09 at 4 09 47 PM](https://user-images.githubusercontent.com/39606064/54078485-fd580b00-4285-11e9-80a9-ff310fd5ef5f.png)

Another Example: Even when you are out of power for the sensor screen, objects will continue to move. In my mind, that should be all grayed out so that the user cannot continue to see objects fly by them. If they don't have enough power, they don't get to see.

**Comment by sassyspock** [comment]
Would it be possible to just remove the ability for there to be negative power draw if the ship is not equipped with battery systems? Then making it so power levels cannot be increased if it is impossible for there to be that extra power?

**Comment by Justintime50** [comment]
That's certainly an option. What would happen when they reach max power? The system shows a pop-up warning saying they have insufficient power and move the slider back to where it last was? I do think something needs to be done as it can be viewed as "broken" if nothing gets put in place.

**Comment by Justintime50** [comment]
@alexanderson1993 did we want to try pursuing this or keep it as is for simplicity and flexibility?

**Comment by alexanderson1993** [comment]
I think we'll keep it as-is for the time being. Flight directors are used to bugging their crews about balancing their power. We'll keep the issue open, though, as it is a valuable feature.

**Comment by Justintime50** [comment]
I'm still a huge fan of this idea (really, my greatest "annoyance" with Thorium), though I can appreciate the massive breaking change this would be to the app and also to the FD ability for story telling so I'm going to close it.
