### ISSUE TITLE
Self Destruct Can Be Started Without Entering a Code

### ISSUE THREAD

**Issue by Justintime50** [Thorium-Sim/thorium#1898]
## Detailed Description

In the command station, you can start the self destruct sequence without setting a deactivation code. I'm not sure if this is by design but I'm sure it can lead to frustrating situations if not. The fix is for the FD to add in a code and then somehow convey that to the crew but that isn't optimal.

**Comment by alexanderson1993** [comment]
This is fixed in the 1.2.0 release.
