### ISSUE TITLE
Better Reporting For Missing Data/Modules

### ISSUE THREAD

**Issue by Justintime50** [Thorium-Sim/thorium#1902]
## Detailed Description

OLD ISSUE: I have all the widgets added to one station and sensors was the final widget. I clicked on the sensors widget and it crashed the thorium client in browser. Has been duplicated after restarting and deleting flight.

EDIT: After playing with it more, I realize that the reason it broke was I didn't have sensors setup in the backend, but the error reporting lended no information at all. It printed a bunch of broken div's and that's it. The error reporting screen would be good under details to show what exactly is wrong. Super helpful while building out sims.

**Comment by Justintime50** [comment]
@alexanderson1993 be aware that sensors was one of a few that broke the system and didn't print error info correctly. I can't remember off hand, I'll report them as I find them, but this wasn't the only one.

**Comment by alexanderson1993** [comment]
Most of them are already handled with a simple "No x system" message. I don't anticipate that there are too many that are broken when systems are missing, but it's possible that there are some.
