### ISSUE TITLE
Damage Teams Screen Isn't Scrollable

### ISSUE THREAD

**Issue by Justintime50** [Thorium-Sim/thorium#1908]
## Detailed Description

On the damage teams screen, depending on your screen size, the bottom controls cannot be reached. Tried in all browsers with the same effect. I was able to see them on my big monitor (24"), but not on the native MacBook Pro 13" screen or another 17" screen. Fix should be scaling UI or scrollable controls. See pic:

![Screen Shot 2019-03-11 at 5 37 14 PM](https://user-images.githubusercontent.com/39606064/54165038-b0f70180-4424-11e9-9f19-1f45398f2d88.png)

**Comment by Justintime50** [comment]
As I'm playing with this, I'm finding it's pretty common on other cards as well. Should we just be scaling down browser sizes then or is there a recommended screen size to view on?

**Comment by alexanderson1993** [comment]
Yes, there are recommended screen resolutions: https://thoriumsim.com/docs/frequently_asked_questions/#docsNav

**Comment by Justintime50** [comment]
Ah perfect. Well, the feature may still be a good request? Maybe not, probably a decent amount of work. Anyway we can warn people when they boot it up what it should be if it's not matching? Either way, I've clarified this in the docs a bit and therefore this may be a closed issue.
