### ISSUE TITLE
Self Destruct Code Cannot Be Set by FD

### ISSUE THREAD

**Issue by Justintime50** [Thorium-Sim/thorium#1946]
## Detailed Description

I know it mentions this in the docs but I didn't see an issue for it so adding here. The FD cannot update the self destruct code on their end and have it reflect on the client end. Additionally, if the FD enters a code on their end, the text box does not update with the new number.

**Comment by alexanderson1993** [comment]
Nah, it looks like changing the code is working just fine. The self destruct countdown is broken though, it would appear.

**Comment by Justintime50** [comment]
![Screen Shot 2019-03-16 at 1 24 16 PM](https://user-images.githubusercontent.com/39606064/54480878-c5a41280-47f3-11e9-9b0a-943e4854c4b4.png)

I get this when trying to update the code on the FD side.
