### ISSUE TITLE
Request: Objects on Sensor Grid Should Gradually Stop When Reset is Pressed

### ISSUE THREAD

**Issue by Justintime50** [Thorium-Sim/thorium#1957]
## Detailed Description

On the sensor grid core, when on the move tab, if objects are in motion and then the reset button is clicked, objects stop suddenly. In space, objects cannot stop suddenly. I propose they come to a gradual stop (this can be done quickly) but will give a much smoother feeling to objects stopping.

**Comment by sassyspock** [comment]
What do you mean by reset button?

**Comment by alexanderson1993** [comment]
On the move tab of the sensor grid core, there is the circle which you can use to make all of the contacts move. Underneath that circle is a yellow button that says ‘Reset’.

**Comment by sassyspock** [comment]
Oh yeah, derp. love that button. Would there be a way to adjust the sensitivity of the move part? I would love to just slow to a stop myself, but it speeds up too fast too soon for me.

**Comment by Justintime50** [comment]
A nice to have, certainly not a bug. I don't plan to work on this myself. Closing.
