### ISSUE TITLE
Request: Border Rotation

### ISSUE THREAD

**Issue by Justintime50** [Thorium-Sim/thorium#1959]
## Detailed Description

On the sensor core, you cannot rotate the border. Since it is an object with an orientation, it would be nice to rotate it 360 degrees. Even if it had 8 different orientations to add some variety instead of the default horizontal view.

**Comment by alexanderson1993** [comment]
This is totally already possible. There is likely a bug keeping that rotation from happening.
<img width="266" alt="Screen Shot 2019-03-18 at 11 11 16 AM" src="https://user-images.githubusercontent.com/6558157/54548964-a1b90c00-496e-11e9-9719-42f619a19af5.png">
