### ISSUE TITLE
Refactor cards with data separation

### ISSUE THREAD

**Issue by alexanderson1993** [Thorium-Sim/thorium#197]
## Detailed Description

Have 'Container' components which get the data from Apollo and push it to the 'View' component. This will make testing much easier and make it so components can be used with different data sources.

**Comment by caseyprovost** [comment]
Hi @alexanderson1993. It looks like there is already a container called CardFrame at `https://github.com/Thorium-Sim/thorium/blob/master/src/containers/Card.js`. Are you looking to also create a subcomponent that render the LayoutComponent?

**Comment by alexanderson1993** [comment]
I’m more worried about the components in the /src/components/views folder, not so much the layouts.

**Comment by alexanderson1993** [comment]
Closing, mainly because this won't cause a ton of benefit for the work required.
