### ISSUE TITLE
Ability to Sync Core Time in Mission Config/Sim Config

### ISSUE THREAD

**Issue by Justintime50** [Thorium-Sim/thorium#1985]
## Detailed Description

It would be nice to be able to configure the time core functionality to be synced in the mission config or the simulator config itself.

**Comment by alexanderson1993** [comment]
This is a client-based configuration - as in it has to be set on individual browsers, so you wouldn't be able to add it into a mission config or simulator config. Also, the checkbox does stay checked between browser refreshes/changing which flight you are running. Outside of that, there's not much that I can do under the circumstances. I'm going to close this issue.
