### ISSUE TITLE
Cannot Add Inventory Count

### ISSUE THREAD

**Issue by Justintime50** [Thorium-Sim/thorium#1995]
## Detailed Description

v1.2.5

Currently you cannot insert a number into the `count` input box for inventory. The input gets highlighted but no cursor, no input.

**Comment by Justintime50** [comment]
I configured decks and rooms and tried assigning inventory to that those areas. Those accepted input but the main count did not. Additionally, after saving, the inventory screen disappears completely and it's blank, it does not save.

**Comment by alexanderson1993** [comment]
The count input is read-only, since you have to change the inventory count for each room. However, it should be putting the total count in that field.
