### ISSUE TITLE
Sync Cores May Not Be Working (Time)

### ISSUE THREAD

**Issue by Justintime50** [Thorium-Sim/thorium#1996]
## Detailed Description

v1.2.5

Syncing cores may not work. Even though the boxes are checked, they don't sync. 

This may have been due to me selecting sync cores after? If so, is there a way that this can be fixed where if synced while a clock is moving (say the FD forgot to sync the core) then it could make the time one?

![Screen Shot 2019-03-22 at 10 30 46 PM](https://user-images.githubusercontent.com/39606064/54862503-b0eae180-4d01-11e9-93b1-e05333bda470.png)

**Comment by alexanderson1993** [comment]
It's really hard for me to know how the Flight Director intends to use this particular feature. For example, what if two timers are going at the same time? Which one gets synced with which.
So it's actually pretty constrained. Checking the box only hints that it wants to sync the time. It only actually syncs the time when one of the timers is re-set. Then, any screens with the core synced will update to that new timer value. However, I think this only applies if the screen is currently open.

**Comment by Justintime50** [comment]
That's a very fair point... Maybe there isn't a great fix then.

**Comment by alexanderson1993** [comment]
Yeah, it's a shame. If you have any suggestions, let me know. Otherwise, I'm going to close this.
