### ISSUE TITLE
Ability to Configure Docking Clamps Attached By Default

### ISSUE THREAD

**Issue by Justintime50** [Thorium-Sim/thorium#1999]
## Detailed Description

v1.2.5

It would be cool to configure the default state of docking clamps in the sim config. (If you started a mission docked, you could have the docking clamps attached by default at the start of the mission.) This just takes one more step off the FD to setup at the beginning of each flight.

**Comment by sassyspock** [comment]
I believe it would be easiest to make it a timeline step, then it could just be added in the initialize step in the mission. Is that about what you were thinking?

**Comment by Justintime50** [comment]
That is certainly an option @sassyspock

**Comment by Emrix** [comment]
I'm going to close this as "Wont Fix" because there is an easy workaround for it.  If there is more desire for this to be a feature, then this issue can be reopened.
