### ISSUE TITLE
Accounts system

### ISSUE THREAD

**Issue by alexanderson1993** [Thorium-Sim/thorium#2]
We need some kind of system for accounts. This will be used to differentiate standard users from admin users and can also be used to keep track of user data across simulator experiences. This is useful for tracking volunteer and flight director hours, student points, the missions which FDs and Students are running, etc. Maybe it could eventually be integrated with a complete online point tracking system.

**Comment by Emrix** [comment]
This is being handled by https://spaceedventures.org/

Closing as "Will not do"
