### ISSUE TITLE
Request: Notification When New Message is in Queue for Review

### ISSUE THREAD

**Issue by Justintime50** [Thorium-Sim/thorium#2004]
## Detailed Description

v1.2.5

There is currently no notification that a message is waiting approval on the comm review card. If someone isn't constantly checking, they may skip right over that functionality (as a user) I've been to sims and hosted sims that have had this concern from users that had messages just sitting in queue because they didn't know it was there.

**Comment by alexanderson1993** [comment]
There actually is a notification on the station with the comm review card. Is there something I'm missing here? Are you referring to perhaps a badge on the card icon or something?

**Comment by Justintime50** [comment]
Hmmm, I'll have to dive in and test it but I had two people now in different sims tell me their messages sat in the review queue because the person using that station didn't know they had pending messages. A badge would be cool, but maybe the notification isn't working? Or potentially it's user error. I'll personally test it to know what's going on.

**Comment by alexanderson1993** [comment]
Any updates on this?

**Comment by Justintime50** [comment]
They must have been blind haha, I see the notification popping up; however, the idea of a badge notification on the station icon is intriguing. I'll leave that up to your better judgement if that's something that should be instituted into Thorium. For instance, on the simulator we ran with only a few people, the 1st officer has 8 screens to go and check so if they weren't constantly going back to that review screen and got busy with other things, they may forget there is something sitting there.

**Comment by alexanderson1993** [comment]
Cool. I'll give this a close. Feel free to comment if you think it should be re-opened.
