### ISSUE TITLE
Damage Reports Can't Be Requested?

### ISSUE THREAD

**Issue by Justintime50** [Thorium-Sim/thorium#2005]
## Detailed Description

v1.2.5

This one will be hard to reproduce as I don't know how we got there, but after awhile in the sim, we could not request a damage report. We broke 4 systems at the same time (from the mission action) and then later manually broke one of those same systems and the engineer could not request a damage report. They'd click the button but nothing would happen, no notification to the FD either.

**Comment by sassyspock** [comment]
Do you happen to remember which systems you broke?

**Comment by Justintime50** [comment]
It was the engines. We broke phasers, torpedos, engines, and thrusters all at once initially as a part of a mission step. They were all requested and then fixed. Later in the sim we broke shields and engines again and those then couldn't be requested.

**Comment by alexanderson1993** [comment]
Any updates on this? I haven't been able to figure out how to reproduce this on my end.

**Comment by Justintime50** [comment]
I've tried to reproduce this as well, probably a fluke. Wanted to report it to see if I could come back to it but nothing, I'll keep an eye out, closing.
