### ISSUE TITLE
Clarify Docking Core Green/Red

### ISSUE THREAD

**Issue by Justintime50** [Thorium-Sim/thorium#2037]
## Detailed Description

It would be super nice, especially for new FD, to be able to know what green/red means. Maybe this is a simple statement on that core saying green is good for flight, or if it clarifies each of the 3 items underneath with their respective status?

![Screen Shot 2019-03-30 at 11 48 52 PM](https://user-images.githubusercontent.com/39606064/55285311-8d99e500-5346-11e9-9f85-2f78623005dc.png)

**Comment by sassyspock** [comment]
That would probably best be solved by clicking the buttons though. You receive docking notifications so after playing around with it for a bit you would figure it out.

**Comment by Justintime50** [comment]
@sassyspock this is true, I'm thinking more along the lines of new FD's; however, this could probably be clarified through better documentation?

**Comment by Emrix** [comment]
It may also be as simple as adding a tooltip over hover on the buttons, so that the state is more clearly understood, but more documentation would never hurt anyone.

**Comment by Justintime50** [comment]
I've added documentation on the card doc for docking about the FD core widget. Hopefully this will clarify. Closing for now.
