### ISSUE TITLE
Dilithium Crystal Stress Notifications

### ISSUE THREAD

**Issue by Justintime50** [Thorium-Sim/thorium#2042]
## Detailed Description

v1.2.9

- The reactor has a notification to the crew when overheating, the dilithium stress level should also have a notification? 
- Also, could the color change to red like the heat level does when it hits a high number (say 90%) so the FD will have some visual cue to look at it? 
- Additionally, it may be nice to toss on a recycle or cycle symbol on that red box to show it's meant to randomly change it?

![Screen Shot 2019-04-01 at 8 28 43 PM](https://user-images.githubusercontent.com/39606064/55371854-f60ad280-54bc-11e9-8e04-cf8915ee3902.png)

**Comment by JordanDeSmith** [comment]
As far as I'm aware there is a notification when it gets too high. 

I'm working on the visual adjustments, including having it turn from blue, to yellow, to red. 
As for the symbol I'm currently thinking of using the same "shuffle" button that's on the random button for course calculation.
