### ISSUE TITLE
Thrusters Don't Send Notifications

### ISSUE THREAD

**Issue by Justintime50** [Thorium-Sim/thorium#2049]
## Detailed Description

v1.2.9

The thrusters should send notifications. I had a user using them for 30 seconds asking the "computer" why we weren't moving on the sensor grid. Maybe they aren't used like that but it may be nice to send the FD a notification the thrusters are in use or changing?

**Comment by sassyspock** [comment]
As an experienced FD I can tell you thruster notifications would get incredibly annoying really quickly. There is an auto-thruster option on the sensors array. That and with auto-nav on the tactical maps, thrusters are significantly easier now than when we had our older controls. I would recommend putting the thruster core widget in a spot you can always see and get a bit of practice down. I can just see the crew that like to just click thrusters repeatedly to move being there and wanting to send a rock through my computer from the notifications. (Yes you can turn off certain notifications but... still.)

**Comment by alexanderson1993** [comment]
@sassyspock The notification could be debounced, so it would only happen every 60 seconds or so. It would allow the flight director to know that the thrusters are being fired so they know to pull up the thruster core, but not frequent enough to cause major dissatisfaction. Also, thruster notifications can always be disabled on the core.

**Comment by Justintime50** [comment]
I totally see both perspectives. The sim I ran had one core screen (not enough real estate to see all the cores at once) and with most everything else shooting off a notification, I could swap in cores as needed. Because it wasn't one of the default cores I had pulled up, I had no idea they were in use. I totally can appreciate the spam on the thrusters though creating insane amounts of notifications, I'm thinking something along the lines of what @alexanderson1993 mentioned where there is a timeout. The notification will only trigger if they have been inactive for 60 seconds or so? That way it picks up on the first thruster use and if they continually use them, the notifications won't come up again until they use them in another circumstance later?

**Comment by Justintime50** [comment]
As I thought about this more, I agree this would get way too noisy. It's a space simulator after all and not everything can be perfect, some amount of "imagination" is needed here and thruster usage is one of them.
