### ISSUE TITLE
Core Feed Shows Random Alert Levels on Flight Start

### ISSUE THREAD

**Issue by Justintime50** [Thorium-Sim/thorium#2050]
## Detailed Description

v1.2.9 (and many of the previous versions)

I have no idea why, but whenever we start a flight, these always show in the core feed. They aren't built into a mission (because no mission is selected) and they always seem to be the same?

![Screen Shot 2019-04-02 at 10 35 50 PM](https://user-images.githubusercontent.com/39606064/55453112-ced50380-5597-11e9-97f6-9fbe43c46a39.png)

**Comment by alexanderson1993** [comment]
That looks like some kind of weirdness in your snapshot. I'm afraid there isn't much I can do to fix that without potentially messing up other people's setups.
