### ISSUE TITLE
Create training videos including commander

### ISSUE THREAD

**Issue by ctolley6** [Thorium-Sim/thorium#206]
Working with the Helpful Penguin Mode, create training videos for beginning the flight that explain each card and have an intro from the captain.

**Comment by isaacOstler** [comment]
With the captain?  Wouldn't that be a bit strange if the captain in the video was different then the ship's captain?  Just have Victor do it, then Admiral Williamson will be universal

**Comment by alexanderson1993** [comment]
This feature is implemented to make it possible to play videos as part of training. The space centers themselves can create their own videos.
