### ISSUE TITLE
Layout Line Showing Blue Screen in Safari

### ISSUE THREAD

**Issue by Justintime50** [Thorium-Sim/thorium#2144]
## Detailed Description

v1.2.18

I use Chrome in while Thorium is actually in use but for quick testing use Safari (default web browser.) The `Layout Line` theme shows a blue screen of death in Safari only, it works fine in Chrome. This started happening in 1.2.16 I believe. (Same thing happens with `Layout Ship Station`.

![Screen Shot 2019-05-06 at 11 17 59 PM](https://user-images.githubusercontent.com/39606064/57273688-01ba5d80-7056-11e9-9b2c-c1a12033779e.png)

**Comment by alexanderson1993** [comment]
Safari actually doesn't support the necessary APIs to render the line layout and layout ship station. It's never been able to show those layouts, and I have no intention of making it possible. Once Safari gets the necessary APIs, it will render properly. Closing as `wontfix`

**Comment by Justintime50** [comment]
👍 thanks boss
