### ISSUE TITLE
Layout Clear Squishing Ship Image

### ISSUE THREAD

**Issue by JordanDeSmith** [Thorium-Sim/thorium#2164]
The clear layout looks really nice, with the exception of the ship image on the login screen. It ends up squished strangely, making the ship look fat. 
![Screen Shot 2019-05-10 at 9 25 52 AM](https://user-images.githubusercontent.com/48338615/57538533-d9f12100-7305-11e9-9a1e-13972567ff2d.png)

**Comment by alexanderson1993** [comment]
Yeah, it’s kinda gross. I missed that. Don’t use the clear layout. I’ll get it fixed in the next update.

Alex
