### ISSUE TITLE
Timeline View Screen

### ISSUE THREAD

**Issue by sassyspock** [Thorium-Sim/thorium#2263]
**Describe the bug**
When pressing play on the timeline core and there is a timeline step to update the view screen to another card (no matter if it is a video or otherwise) will not adjust the view screen in any way. Using the view screen core works without issue. Restarting the server generally corrects the issue.
Not entirely sure what causes the bug, but my hypothesis is below.

**To Reproduce**
1. Download update of Thorium.
2. Begin mission, press play on timeline core.
3. Nothing changes on view screen.
4. Cry.
5. Close server and open again.
6. Timeline now updates view screen again.
7. Breathe and celebrate.

**Expected behavior**
Pressing play on the timeline when there is a step that changes the view screen updates the view screen.

**Comment by alexanderson1993** [comment]
Is this still happening? The information you've given isn't much for me to go on. I'm wondering if there are more specific things that have to happen for this bug to occur.

Is the viewscreen client browser refreshed when the update is installed?

(I tried crying, but that didn't seem to make a difference)

**Comment by sassyspock** [comment]
This bug seems to just pop up infrequently. If it happens again I can get you more details, but at the moment that is all I know.

**Comment by alexanderson1993** [comment]
Cool. Open a new issue if you discover anything more. Until then, I'm going to close this issue.
