### ISSUE TITLE
Mobile App Crashing

### ISSUE THREAD

**Issue by JordanDeSmith** [Thorium-Sim/thorium#2314]
**Describe the bug**
The mobile app crashes when trying to load any screen assigned from core. 

**To Reproduce**
1. Connect mobile app to server
2. Try to assign the client phone a station.

**Expected behavior**
Expected not to crash. 

**Screenshots**
![Image-1](https://user-images.githubusercontent.com/48338615/59217343-f8537200-8b7a-11e9-8466-d0b17579336c.jpg)

**Comment by alexanderson1993** [comment]
This is fixed with an OTA update.
