### ISSUE TITLE
Dynamic Layout crashes on edit without any cores loaded

### ISSUE THREAD

**Issue by JordanDeSmith** [Thorium-Sim/thorium#2326]
**Describe the bug**
If there are no core modules open on dynamic core 
<img width="588" alt="Screen Shot 2019-06-11 at 11 22 05 AM" src="https://user-images.githubusercontent.com/48338615/59292890-2b5d3a80-8c3b-11e9-8518-32c8e7cc2018.png">
Then when clicking to enter edit mode, core will crash. 
<img width="1112" alt="Screen Shot 2019-06-11 at 11 23 00 AM" src="https://user-images.githubusercontent.com/48338615/59292945-4fb91700-8c3b-11e9-985c-4dfd8d6cf2e8.png">

**To Reproduce**
1. Go to dynamic or next core
2. Make sure there are no core modules loaded.
3. Click edit
Alternate if there are already core modules loaded: 
1: Go to dynamic or next core
2: Click edit
3: Click the "X" to close out of every module
4: Upon clicking the "X" to close the last one, the error will appear. 

**Expected behavior**
Not crashing.

**Comment by alexanderson1993** [comment]
These are good reproduction instructions. Thank you!
