### ISSUE TITLE
Erratic Docking

### ISSUE THREAD

**Issue by JordanDeSmith** [Thorium-Sim/thorium#2338]
**Describe the bug**
When clicking the different docking control buttons on the crew side docking control it sometimes requires multiple clicks before it actually changes. It will update on core before it updates on the helm/flight control station until the station is refreshed. Leading to multiple notifications that, for example, the clamps are detached as the crew keeps trying to detach them never seeing any different, as it will appear that nothing is happening apart from the docking buttons being temporarily disabled. 

**To Reproduce**
It's erratic enough that it's hard to describe exactly what is happening. But if you go to docking control and start trying to undock and dock, it will be apparent. It does appear to occur mostly after the first time an action has been completed. Clicking for the airlocks or ramps the first time will generally work fine, but afterwards will have this issue. 

**Expected behavior**
Everything should detach, retract, attach, etc. on the first click, updating properly on both core and the station.

**Comment by sassyspock** [comment]
![Screen Shot 2019-06-18 at 3 40 59 PM](https://user-images.githubusercontent.com/43680869/59721936-a7c5bf80-91df-11e9-958c-ff56506bb3df.png)
