### ISSUE TITLE
Panel support for Stations

### ISSUE THREAD

**Issue by alexanderson1993** [Thorium-Sim/thorium#25]
Make it so panels appear as clients on the Thorium server; have stations specifically for hardware panels which don't have cards, but can still initialize to a specific simulator and send messages as part of that flight.

**Comment by brentjanderson** [comment]
Having a protocol that enables the interactions here is the critical factor - whether that's GraphQL or HTTP or Meteor's DDP. At that point, it doesn't matter what your client is - it "just works".

**Comment by alexanderson1993** [comment]
This is basically handled by the current client implementation - it's possible for panels to appear in Thorium as clients. They likely wouldn't need to be assigned a station, since they would be their own thing.
