### ISSUE TITLE
Simulator#Lighting should provide more data to have a more fine grained control over the scenes in luminave

### ISSUE THREAD

**Issue by TimPietrusky** [Thorium-Sim/thorium#2572]
In order to have more control of the lighting inside the simulator, it would be nice to get more information out of Thorium in the `Simulator#Lighting` API endpoint instead of just the current color that already was translated by Thorium based on something else that happened (for example an Alert level change).

## Use Cases

- Status of the flight (started, ended, paused, running) so when the flight is done we do not switch off all lights, see #2570
- What is the current alert level

## Solution
Extend the GraphQL API on `Simulator#Lighting`

## Alternatives
Mapping the corresponding alert level colors to scenes in luminave, but that is very confusing in the future and might also break if a browser would send something else for a certain color. 

## Additional context
In https://github.com/NERDDISCO/luminave-thorium/issues/9 I created an issue for the alternative "alert levels", but I would love to actually use the enhanced data from Thorium to make this as flexible as possible. 

Also when this gets implemented, it will be a lot easier to support the  use case "Alerts" in https://github.com/NERDDISCO/luminave/issues/110

**Comment by TimPietrusky** [comment]
@alexanderson1993 do you have any other use cases where data from Thorium could be used to control lights that I forgot?

**Comment by alexanderson1993** [comment]
As it turns out, alert level and flight status can be accessed via GraphQL already. `alertlevel` is available in the Simulator query:

```graphql
query Lighting($id: ID!) {
  simulators(id: $id) {
    id
    alertlevel
	lighting {
	  intensity
	  action
	  actionStrength
	  transitionDuration
	  useAlertColor
	  color
	}
  }
}
```

And you can get the flight running status from the client query:

```graphql
query Client($clientId: ID!) {
    clients(clientId: $clientId) {
		flight {
		  id
		  name
		  running
		}
    }
  }
```

If `flight` returns a null value, then the client hasn't been assigned to a flight, which means no flight is currently running.

Pretty much all data in Thorium can be accessed via the GraphQL API.

**Comment by TimPietrusky** [comment]
@alexanderson1993 thank you!
