### ISSUE TITLE
Procedural Universe Creation

### ISSUE THREAD

**Issue by alexanderson1993** [Thorium-Sim/thorium#26]
Have the universe created procedurally. Use some kind of cool algorithm? #pieInTheSky

**Comment by Emrix** [comment]
This could be similar to https://www.nomanssky.com

**Comment by alexanderson1993** [comment]
Closing, due to this being rolled up into an RFC: https://docs.google.com/document/d/11OkHwpWn_M--DMWxPvP77S3JVt2Ni6Jxw1h2YK546Pw/edit?usp=sharing
