### ISSUE TITLE
Kiosk 2.0.8 jittering on viewscreen

### ISSUE THREAD

**Issue by JordanDeSmith** [Thorium-Sim/thorium#2621]
**Describe the bug**
Using 2.0.8 kiosk as a viewscreen causes jittering of moving elements. 

**To Reproduce**
Start a 2.0.8 kiosk and set it to a viewscreen. 
Show something moving, such as forward scans (this was the most obvious.)
It's more prominent after being partway through a flight when there has been more load on the server. 

**Expected behavior**
It should be smooth, such as it was in the previous kiosk. 

**Screenshots**
￼￼￼I have a video of it but it won't let me upload it here, so I'll send it in an email to Alex. 

**Additional context**
It wasn't as noticeable at the beginning of the flight, but 45 minutes or so in it was getting pretty bad.

**Comment by alexanderson1993** [comment]
I wasn't able to reproduce this, but it's possible it requires much longer testing period, like 45 minutes or so.
