### ISSUE TITLE
Intership vocal communications

### ISSUE THREAD

**Issue by tdelc** [Thorium-Sim/thorium#2682]
**Is your feature request related to a problem? Please describe.**

Sorry if it is obvious, but I don't understand how to create a simulation with two ships which can create vocal communication between them (in the short range panel). On the same subject, is it possible to create a vocal call between Core and Client ? When I accept communication, I have the confirmation but nothing append.

**Describe the solution you'd like**

If it already exist, a tutorial to explain this feature.

**Comment by alexanderson1993** [comment]
Hi Thomas,

There currently isn't a way to create a simulation with two ships that can communicate one with another. There also isn't a way to create an audio connection between Core and Clients.

The way the Short Range screen currently works is with the communication connection being a signal to the flight director to start talking over a microphone and sound system or an telephone intercom or something like that. The controls don't facilitate the audio - yet. 

I'm planning on adding this feature sometime in the future (detailed here: https://github.com/Thorium-Sim/thorium/issues/2627). I'm also planning on creating a complete audio system for aggregating sound effects, voice audio with a voice changer, music, and ambiance. Those are outlined in the following RFCs:


- Voice Changer: https://docs.google.com/document/d/1KyYcymwuiAmQki0e45xAIycHSFy_eOmgB9uV-s5xiag/edit?usp=sharing
- Sound Board & Sound Players: https://docs.google.com/document/d/1wyyB_VxnLRQTNapW-aCM6ojsHl54sbYS2SOP8Ac3TME/edit?usp=sharing
- Music Player: https://docs.google.com/document/d/1WW7hc9b-jCqDTtZxtp_KMvpdGay_CRO3BHXDXI3eZGg/edit?usp=sharing

Once the first two RFCs are implemented, it should be possible to establish communication lines between two ships in the same simulation, as well as connect the core to the clients for NPC conversations.

I'll add some documentation to https://thoriumsim.com to indicate that those audio connections should be done outside of Thorium for the time being.

**Comment by tdelc** [comment]
Ok, thanks for this explanations. And theses features look great !
