### ISSUE TITLE
no option to update

### ISSUE THREAD

**Issue by 19ibaker** [Thorium-Sim/thorium#2691]
## Detailed Description
i was loading up 2.1.0 and it was not telling me 2.2.0 was released, i ended up having to go back to the thoriumsim site to get the 2.2 update. i think it would be beneficial to have the option to update thorium, or at least notify us when a new update is released

**Comment by alexanderson1993** [comment]
Good news! This is fixed in 2.3! Comes out sometime next week.

Thanks for filing the issue though!
