### ISSUE TITLE
Importing Crew From CSV Doesn't Work

### ISSUE THREAD

**Issue by SideMatter** [Thorium-Sim/thorium#2761]
**Describe the bug**

Importing CSVs for crew is broken

**To Reproduce**

1. Create CSV with all the correct parameters 
2. Import into thorium
3. Observe
**Expected behavior**

Crew Members Import
**Screenshots**

![Screen Shot 2020-02-12 at 11 55 36 AM](https://user-images.githubusercontent.com/33376632/74367203-b3797e00-4d8e-11ea-8cc7-3d10e8f3d445.png)
![Screen Shot 2020-02-12 at 11 55 48 AM](https://user-images.githubusercontent.com/33376632/74367208-b6746e80-4d8e-11ea-80c0-c6ff857585fc.png)

**Additional context**

You are amazing alex

**Comment by alexanderson1993** [comment]
This has been fixed in versions 2.x and up. Closing.
