### ISSUE TITLE
Incorrect GraphQL server address on startup

### ISSUE THREAD

**Issue by Emrix** [Thorium-Sim/thorium#284]
## Detailed Description

Among the startup messages in the terminal when Thorium is started, it gives the incorrect URL for the graphQL server.  It is missing the "i" in "graphiql"
"GraphQL Server is now running on http://localhost:3001/graphql" is what it is currently showing.

"GraphQL Server is now running on http://localhost:3001/graphiql" is what it should be.

**Comment by alexanderson1993** [comment]
What is there is actually correct. The GraphQL server is the api server; GraphiQL is a front end for accessing that server. Slight distinction. I could add another line explaining where to access GraphiQL in addition to the other lines.
