### ISSUE TITLE
Update CHANGELOG to include updates from 3.0.0+

### ISSUE THREAD

**Issue by Justintime50** [Thorium-Sim/thorium#3030]
**Describe the bug**

Currently, the CHANGELOG is still on `2.x` and needs to be updated to include changes from `3.x`.

**Expected behavior**

The CHANGELOG should contain up-to-date info on what was changed in each version.

**Additional context**

NA

**Comment by alexanderson1993** [comment]
Good catch. It's actually been broken for a few releases. I'm publishing an update to the website right now that fixes it. Check it in 10 minutes or so.

Note that the release notes in the app are still working correctly.
