### ISSUE TITLE
Bugs & Minor Features

### ISSUE THREAD

**Issue by alexanderson1993** [Thorium-Sim/thorium#322]
## Detailed Description

- [x] Simulator systems config

- [x] Crew config

- [x] Roster pool & auto crew composition

- [x] Damage Report Length

- [x] Short Range Comm sine waves

- [x] 3D Model on Thrusters

- [x] Power available and power draw on Power Distribution screen

- [x] Advanced navigation: Can't drag thruster arrow when it is on bottom

- [x] Named tractor beam targets

- [x] Shield frequency faster

- [x] Add hashtag for simulator name as part of mission configurations
  - Sensor Presets
  - Sensors Processed Data
  - Long Range Message
  - Change viewscreen or apply data
- [x] Delete Sets
- [x] Delete inventory
- [x] Improve inventory management
- [x] Inventory core
- [x] Delete tactical maps
- [x] Fix reset flight
- [x] Activate stealth field from core
- [x] INternal comm core black text
- [x] No typing in course when typing destination on navigation
- [x] Required thrusters not changing on crew card
- [x] Long range comm blank damage step
- [x] Reactivation code funky
- [x] Damage team not showing up in messaging list
- [x] Coolant system ordering on coolant card
- [x] Voyager torpedo coloring
- [x] Notification for torpedos and phasers
- [x] Top power bar in power distribution
- [x] Overload reactor power level
- [x] Reactor heat
- [x] Option key sensors presets typing in the thing. preventdefault
- [x] No longer hover sensor contacts when un-pinged
- [x] Probes not showing up in probe control screen
- [x] Core for Tranzine Gas
- [x] Communications viewscreen breaks
- [x] Better loading indicator for loading missions 
- [x] Auto-Cycle through viewscreens when in context
- [x] JR Comm ‘Incomming’ spelled wrong
- [x] JR Sensors hover
- [x] Navigate away from core when the flight is over
- [x] Cargo screen finding goes out of bounds
- [x] Timer clock
- [x] Dice of Doom
- [x] Improve sensor contact config
- [x] Darken ask for speed text
- [x] Simplfy asset system. Abstract away containers and objects
- [x] Logout clients when flight resets
- [x] Odyssey layout "station.cards.map" on viewscreen
- [x] Sensors History & Yaw Pitch Roll nav on system config
- [x] Cannot read proeprty 'cool'
- [x] Nav not finishing course sending (might be false alarm)
- [x] On error screen refresh, clear localstorage
- [x] No notifications on core
- [x] Weapons range on sensors adds to targeting
- [x] Ship core - Cannot change simulator layout
- [x] Engines still broken after flight deleted and restarted
- [x] Sensor info not populated from timeline macro
- [x] Line up mouse cursor with dragging army contacts
- [x] Viewscreen previews - thumbnails for each of the viewscreens
- [x] Make it so viewscreen cursor shows up on viewscreen manager
- [x] Internal sensors viewscreen layout and functionality issues
- [x] Damage team messages not showing up
- [x] Coolant did somethign weird when I changed it.
- [x] Comm arrow not showing up on Short Rnage Comm

**Comment by Emrix** [comment]
- [ ] Delete button on damage optional steps don't show up (cannot delete optional steps in simulator config)

**Comment by alexanderson1993** [comment]
@Emrix Good catch. Master branch is updated with a fix for that.
