### ISSUE TITLE
Can't start application (yarn install throws errors)

### ISSUE THREAD

**Issue by Darokrithia** [Thorium-Sim/thorium#3325]
I'm unable to get thorium to work for me.  I installed yarn via homebrew (using Mac OSX 12.6 with M1 chip FWIW), but I am unable to get yarn install to run, nor the other following commands (yarn start and yarn build).

Yarn gives a number of warnings about version errors before failing.  For example:

```warning "@apollo/client > graphql-tag@2.10.3" has incorrect peer dependency "graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0".
warning "@apollo/link-context > @apollo/client@3.0.0-beta.32" has incorrect peer dependency "graphql@^14.5.4".
warning "apollo-server-express > graphql-subscriptions@1.1.0" has incorrect peer dependency "graphql@^0.10.5 || ^0.11.3 || ^0.12.0 || ^0.13.0 || ^14.0.0".
warning " > subscriptions-transport-ws@0.9.16" has incorrect peer dependency "graphql@^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.1 || ^14.0.2".
```

This goes on for a while, with many packages seeming to have 'incorrect peer dependencies'

Finally the actual error and stack trace is as such:

```
warning Error running install script for optional dependency: "~/thorium/node_modules/chokidar/node_modules/fsevents, ~thorium/node_modules/jest-haste-map/node_modules/fsevents: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: ~/thorium/node_modules/chokidar/node_modules/fsevents
Output:
node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: spawn node-gyp ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn node-gyp',
  path: 'node-gyp',
  spawnargs: [ 'rebuild' ]
}

Node.js v20.5.1"
info This module is OPTIONAL, you can safely ignore this error
error ~thorium/node_modules/@serialport/bindings: Command failed.
Exit code: 127
Command: prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
Arguments: 
Directory: ~/thorium/node_modules/@serialport/bindings
```

I haven't used yarn or node much, and I'm not sure how to fix this issue.  Any advice is appreciated.  I tried updating node and yarn, but neither seemed to fix this.

**Comment by alexanderson1993** [comment]
See if you can run it with Yarn 1 and Node 12, and let me know how it goes. On an M1, you'll have to run Node 12 in Rosetta, which should happen automatically if you've activated Rosetta already.

**Comment by Darokrithia** [comment]
To be totally honest with you, I don't exactly know what that means.  Is yarn 1 a version of yarn (same with node 12)?  I'll look into backdating them.

**Comment by alexanderson1993** [comment]
Yep. Just older versions. Thorium Classic hasn't been updated to use newer versions.

 Installation instructions for Yarn 1 here. https://classic.yarnpkg.com/lang/en/docs/install/#mac-stable

I like to use Volta, which lets me manage versions of multiple tools, including Node and Yarn. https://volta.sh

**Comment by Darokrithia** [comment]
I installed volta (and n) and am having a lot of difficulty still.  I think some of the issue is that node is also installed as a dependency of other brew packages (such as jupyter).  I unlinked node from homebrew, which let me properly switch node's version away from 20.5.1 to 12.22.12 (according to node -v).  This threw a different error when running yarn install

```
/opt/homebrew/lib/node_modules/corepack/dist/lib/corepack.cjs:5364
        return this[INTERNAL].defaultPort ?? (this.protocol === "https:" ? 443 : 80);
                                           ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/homebrew/lib/node_modules/corepack/dist/yarn.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

Not sure what this means and if its better or worse than before haha

**Comment by Darokrithia** [comment]
I also tried ```volta run yarn```  but this gives a new error:

```
[2/4] 🚚  Fetching packages...
error pdfjs-dist@3.10.111: The engine "node" is incompatible with this module. Expected version ">=18". Got "14.21.3"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

FWIW, volta list gives the following output:

```
⚡️ Currently active tools:

    Node: v14.21.3 (current @ ~/thorium/package.json)
    Yarn: v1.22.19 (default)
    Tool binaries available:
        n (default)
```

I ran volta install node@12, but this returns
```
success: installed and set node@12.22.12 (with npm@6.14.16) as default
   note: you are using node@14.21.3 in the current project
```

**Comment by Darokrithia** [comment]
I eventually got this working by using volta and doing some git resets.  Not sure exactly what was wrong.  Thanks for the help.  I would add the need to use volta to the documentation if other people have this issue.  Most likely it was a one off thing haha
