### ISSUE TITLE
Links at bottom are not visible on hover.

### ISSUE THREAD

**Issue by Rishabh705** [Thorium-Sim/thorium#3336]
Links at bottom (About and Blog) are not visible on hover.

1. Go to 'https://thoriumsim.com/'
2. Scroll down to bottom of page.
3. Hover on 'About' or 'Blog'.

Expected behavior

On hovering, links should be visible to user.

**Comment by Rishabh705** [comment]
Sir/mam,
Can i work on this?

**Comment by alexanderson1993** [comment]
This should have been filed in the thorium-sim/thoriumsim.com repo, and this has already been addressed in a rewrite which hasn't been released yet.  Closing.
