### ISSUE TITLE
Event Connector

### ISSUE THREAD

**Issue by alexanderson1993** [Thorium-Sim/thorium#687]
## Detailed Description

Create the ability for Thorium to trigger macros based on an event which happens in the simulation. Flight directors can configure which macro is run for what events. Events could include "Fire Torpedo", "Fire Phasers", "External Scan", etc.

Perhaps it could use an ECS-style component system for grabbing events, pulling the data from the events, and performing conditionals based on the data in the event. For example, I want to play a different sound for if a photon torpedo is launched vs. a quantum torpedo.

**Comment by brentjanderson** [comment]
It sounds like thorium is going to need to be turing complete before it’s “done”
