### ISSUE TITLE
Documentation? Screenshots? React-Storybook?

### ISSUE THREAD

**Issue by kimballfrank** [Thorium-Sim/thorium#948]
Is there some documentation of screens and states?

I did find these screenshots: https://github.com/Thorium-Sim/thorium/tree/master/public/viewscreen

Still, something like React-storybooks would be great to keep an eye on how things are looking without having to get the whole system into a particular state.

I’m interested in contributing to the UI/UX and to the general richness of the Thorium experience. 

But I am having a hard time grasping the full scope of the system. Hence, it would be great to see some additional documentation.

I realize tons of time and energy has been poured into this project already, and I just want to help! I realize I am an outsider without all the facts, so take all this for whatever it’s worth.

**Comment by alexanderson1993** [comment]
Glad to have you aboard!

The project website at https://thoriumsim.com has a number of documentation pages and screenshots for the various screens. It's incomplete, but you can see the ones that have been completed there. For example, I recently added a page for the THX screen, which can be found here: https://thoriumsim.com/docs/card_thx

That documentation site also explains some of the intentions and the scope of the project. If you haven't already, just start at the top and work your way down through that first overview section.

I unfortunately didn't architect Thorium to work well with a React-Storybooks system from the get-go, so I don't know how hard it would be to implement something like that. Any suggestions on that front are appreciated.

**Comment by Justintime50** [comment]
@kimballfrank I've recently documented most of the screens and cards you'll come across in Thorium with descriptions and pictures, hopefully there is more info there now that could fill in the blanks? Check out the docs again.

**Comment by Emrix** [comment]
I'm going to go ahead and close this issue for now, unless the intention of this was to request an enhancement to use React-Storybook.
For documentation and updating it, see thoriumsim.com, and for discussion on documentation, see the #documentation channel on the [Thorium Discord](https://discordapp.com/invite/UvxTQZz)
